import random

# Number of test to be generated
tests = 100
# Max sum to be tested
max_sum = 10000
# Max results to be generated by each sum
max_results = 10
# Min length for list of inputs
min_input_len = 100

lines = []
for y in range(0, tests):

    aresults = []
    ainputs = []

    # get a sum
    asum = random.randint(0, max_sum)

    # Number of results
    for x in range(0, random.randint(0, max_results)):
        aresult = asum - random.randint(-max_sum, max_sum)
        aresults.append(aresult)
        aresults.append(asum - aresult)

    while len(ainputs) < min_input_len:
        i = random.randint(-max_sum * 10, max_sum * 10)
        if i not in ainputs:
            ainputs.append(i)

    for j in aresults:
        if j not in ainputs:
            ainputs.append(j)

    print('aresults: ', aresults)
    print('ainputs: ', ainputs)
    print('asum: ', asum)
    print('')

    # sorted(ainputs, key=lambda o: random.random())
    random.shuffle(ainputs)

    lines.append(f"{','.join(str(x) for x in ainputs )} {asum} {','.join(str(x) for x in aresults)}")

file = open('tests.txt', 'w+')
file.writelines('\n'.join(lines))
file.close()
